# **Media Prediction Data Construction**

In [ ]:
import pandas as pd
import ast
import os
import sys
sys.path.append("..")

from tqdm import tqdm
from io import StringIO

import requests
import re
from requests.adapters import HTTPAdapter, Retry

from Bio.KEGG import REST
import modules.utils as utils

In [ ]:
DATA_DIR = "~/Desktop/Projects/Media_Prediction/media_prediction/data" # Replace with your working directory
#DATA_DIR should have sub-directories "bacdive", "cofactors", "concentrations", "kegg", "MAGs", "mediadive", and "uniprot"

# Build Training Dataset:

## Media and Associated Taxa

1.1 MediaDive | Provides media IDs, components/annotations, associated taxa, and other relevant information

1.2 BacDive | Provides culture/isolation info, metabolic annotations (including EC and metabolites), and more (1.1)

### [1.1] MediaDive

In [2]:
import modules.mediadive as md

# Retrieve all available media from MediaDive
md_media_df = md.get_media()
md_media_df.to_csv(os.path.join(DATA_DIR, "mediadive", "mediadive-media.csv"), index=False) #SAVE

In [3]:
# Create media_id_list
md_media_df = md_media_df.rename(columns={"id": "media_id"})
media_id_list = md_media_df["media_id"].astype(str).unique()

# Use media_id_list to retrieve media composition information
md_comp_df = md.get_composition(media_id_list)

# Use media_id_list to retrieve media-associated strain information
md_strains_df = md.get_strains(media_id_list)

md_comp_df.to_csv(os.path.join(DATA_DIR, "mediadive","mediadive-media-comp.csv"), sep=";", index=False) #SAVE
md_strains_df.to_csv(os.path.join(DATA_DIR, "mediadive", "mediadive-media-strains.csv"), sep=";", index=False) #SAVE

100%|██████████| 3324/3324 [46:56<00:00,  1.18it/s]
100%|██████████| 3324/3324 [34:29<00:00,  1.61it/s]

In [4]:
# Merge media composition and strains info
md_df = pd.merge(left=md_comp_df, right=md_strains_df, on="media_id", how="outer", indicator=True)
md_df = pd.merge(left=md_media_df, right=md_df, on="media_id", how="left", indicator=False)

# Indicate data sources
md_df = md_df.rename(columns={"_merge": "merge_source"})
md_df["merge_source"] = md_df["merge_source"].cat.rename_categories({"right_only": "composition_only", "left_only": "strains_only"})

md_df.to_csv(os.path.join(DATA_DIR,"mediadive","mediadive-all.csv"), sep=";", index=False) #SAVE
md_df.head()

,media_id,name,complex_medium,source,link,min_pH,max_pH,reference,description,components,component_ids,strain_id,species,ccno,bacdive_id,merge_source
0,1,NUTRIENT AGAR,1,DSMZ,https://www.dsmz.de/microorganisms/medium/pdf/...,7.0,7.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1a,REACTIVATION WITH LIQUID MEDIUM 1,1,DSMZ,https://www.dsmz.de/microorganisms/medium/pdf/...,7.0,7.0,None,None,"[Peptone, Meat extract, Agar, Distilled water]","[1, 2, 3, 4]",29.0,Comamonas testosteroni,DSM 38,2912.0,both
2,1a,REACTIVATION WITH LIQUID MEDIUM 1,1,DSMZ,https://www.dsmz.de/microorganisms/medium/pdf/...,7.0,7.0,None,None,"[Peptone, Meat extract, Agar, Distilled water]","[1, 2, 3, 4]",30.0,Delftia acidovorans,DSM 39,2941.0,both
3,1a,REACTIVATION WITH LIQUID MEDIUM 1,1,DSMZ,https://www.dsmz.de/microorganisms/medium/pdf/...,7.0,7.0,None,None,"[Peptone, Meat extract, Agar, Distilled water]","[1, 2, 3, 4]",39.0,Acidovorax delafieldii,DSM 64,2885.0,both
4,1a,REACTIVATION WITH LIQUID MEDIUM 1,1,DSMZ,https://www.dsmz.de/microorganisms/medium/pdf/...,7.0,7.0,None,None,"[Peptone, Meat extract, Agar, Distilled water]","[1, 2, 3, 4]",52.0,Pseudomonas putida,DSM 84,12895.0,both

### [1.2] BacDive

In [5]:
import modules.bacdive as bd

# Retrieve bacdive_id's from the 'md_df' MediaDive table
md_df = pd.read_csv(os.path.join(DATA_DIR, "mediadive", "mediadive-all.csv"), sep=";")
bd_id_list = md_df["bacdive_id"].dropna().astype(int).astype(str).unique()
print(len(bd_id_list), "strains")

13916 strains

In [ ]:
# Initialize BacDive client
from dotenv import load_dotenv
load_dotenv()

import bacdive
from bacdive import BacdiveClient

BACDIVE_USER = os.getenv("BACDIVE_USER")
BACDIVE_PASS = os.getenv("BACDIVE_PASS")

client = BacdiveClient(BACDIVE_USER, BACDIVE_PASS)

-- Authentication successful --

In [ ]:
# Retrieve BacDive info
step = 100
bacdive_df = []

for idx_start in tqdm(range(0, len(bd_id_list), step)): #status bar
    id_list = ";".join(bd_id_list[idx_start:idx_start+step]) 
    bacdive_df.append(bd.taxon2ec(id_list=id_list, client=client))

bacdive_df = pd.concat(bacdive_df, axis=0, ignore_index=True)
bacdive_df = bacdive_df.drop("reference", axis=1)
bacdive_df['taxon_id'] = bacdive_df['taxon_id'].astype(str)
bacdive_df['taxon_id'] = bacdive_df['taxon_id'].str.split(';').explode('taxon_id')

bacdive_df.to_csv(os.path.join(DATA_DIR, "bacdive", "bacdive-all.csv"), index=False) #SAVE
bacdive_df.head()

100%|██████████| 140/140 [04:18<00:00,  1.85s/it]

,general_@ref,bacdive_id,dsmz_id,general_keywords,general_description,taxon_id,ncbi_tax_id_matching_level,strain_history_@ref,strain_history_history,general_doi,...,isolation_sampling_date,physiology_and_metabolism_murein,physiology_and_metabolism_api_list,isolation_enrichment_culture,isolation_enrichment_culture_temperature,multicellular_morphology_complex_color,api_list_beta_hem,metabolite_tests_citrate_test,compound_production_excreted,isolation_enrichment_culture_duration
0,21113,24370,11532.0,"[Bacteria, mesophilic, animal pathogen]",Pseudomonas fluorescens PWD34 is a mesophilic ...,294,species,21113.0,"<- W. Duetz, RIVM, Bilthoven; PWD34",10.13145/bacdive24370.20241212.9.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21111,24368,304.0,"[Bacteria, mesophilic]",Pseudomonas sp. DSM 304 is a mesophilic bacter...,306,species,21111.0,"<- IMG, 1591 (<i>P. fluorescens</i>) <- H. Stolp",10.13145/bacdive24368.20241212.9.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20542,23995,30059.0,"[Bacteria, mesophilic]",Lelliottia amnigena 21824 is a mesophilic bact...,61646,species,20542.0,<- Bakteriologisches Institut der Sueddeutsche...,10.13145/bacdive23995.20241212.9.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1479,17621,3849.0,"[16S sequence, Bacteria, mesophilic, plant pat...",Xanthomonas citri subsp. malvacearum XM13 is a...,346,species,NaN,NaN,10.13145/bacdive17621.20241212.9.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1480,17596,3850.0,"[genome sequence, Bacteria, obligate aerobe, m...",Xanthomonas campestris DSM 3850 is an obligate...,339,species,NaN,NaN,10.13145/bacdive17596.20250331.9.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Taxa to EC

2.1 UniProtKB (species) | Queries UniProtKB for ec numbers from an input of species names (1.1)

2.2 UniProtKB (taxon_id) | Queries UniProtKB for ec numbers from an input of NCBI taxon_id's (1.2)

2.3 Final taxa2ec dataframe | Formatting identifiers and associated ec numbers (1.2, 2.1, 2.2)

### [2.1] UniProtKB (species)

In [8]:
# Format species names
species_df = pd.read_csv(os.path.join(DATA_DIR,"mediadive","mediadive-all.csv"), sep=";", low_memory=False)
species_df['species'] = species_df['species'].replace(' ','+', regex=True)
species_list = set(species_df['species'].to_list())
print(len(species_list), "species")

12476 species

In [9]:
# Import and run function to retrieve ec's associated with each species
    # Note: currently, script only checks reviewed entries (SwissProt), and ignores 1000's of tREMBL entries
    # Errors represent where species are totally absent, whereas non-reviewed entries show as 'x species with no data'

import modules.uniprot as uni

uniprot_df = uni.species2ec(species_list)
uniprot_df.to_csv(os.path.join(DATA_DIR, "uniprot", "uniprot-all.csv"), index=False) #SAVE

Processing species:  38%|███▊      | 4724/12476 [26:41<1:06:32,  1.94it/s]

HTTP error occurred for Protocrea+illino&euml;nsis: 400 Client Error: Bad Request for url: https://rest.uniprot.org/uniprotkb/search?fields=accession%2Cec%2Corganism_name%2Corganism_id%2Ccc_cofactor%2Cid&format=tsv&size=500&query=%28organism_name%3AProtocrea+illino&euml;nsis%29+AND+%28ec%3A*%29+AND+%28reviewed%3Atrue%29

Processing species:  38%|███▊      | 4751/12476 [26:50<53:56,  2.39it/s]

HTTP error occurred for Sphingobacterium+composti+[homonym]: 400 Client Error: Bad Request for url: https://rest.uniprot.org/uniprotkb/search?fields=accession%2Cec%2Corganism_name%2Corganism_id%2Ccc_cofactor%2Cid&format=tsv&size=500&query=%28organism_name%3ASphingobacterium+composti+%5Bhomonym%5D%29+AND+%28ec%3A*%29+AND+%28reviewed%3Atrue%29

Processing species: 100%|██████████| 12476/12476 [1:10:43<00:00,  2.94it/s]

10711 species with no data

### [2.2] UniProtKB (taxon_id)

In [10]:
bacdive_df = pd.read_csv(os.path.join(DATA_DIR, "bacdive", "bacdive-all.csv"), low_memory=False)

# Filter nan and/or joined IDs
bacdive_df['taxon_id'] = bacdive_df['taxon_id'].astype(str) # string to filter
nan = bacdive_df['taxon_id'].str.contains("nan")
bacdive_df = bacdive_df[~nan]
bacdive_df['taxon_id'] = bacdive_df['taxon_id'].astype('f8') # back to float (no string->integer)
bacdive_df['taxon_id'] = bacdive_df['taxon_id'].astype(int) # integer for search

print(len(bacdive_df), "species-level taxon_ids")

13773 species-level taxon_ids

In [11]:
tax_ids = bacdive_df['taxon_id'].to_list()

ncbi_df = uni.taxon2ec(tax_ids)
ncbi_df['ec_uniprot'] = ncbi_df['ec_uniprot'].str.split('; ').explode('ec_uniprot')

ncbi_df.to_csv(os.path.join(DATA_DIR, 'bacdive', 'ncbi-ec.csv'), index=False) #SAVE

Processing species: 100%|██████████| 13773/13773 [4:04:21<00:00,  1.06s/it]

3408 species with no data

### [2.3] Final taxa2ec table

In [12]:
bacdive_df = pd.read_csv(os.path.join(DATA_DIR, 'bacdive', 'bacdive-all.csv'), low_memory=False)
uniprot_df = pd.read_csv(os.path.join(DATA_DIR, 'uniprot', 'uniprot-all.csv'))
ncbi_df = pd.read_csv(os.path.join(DATA_DIR, 'bacdive', 'ncbi-ec.csv'))

# BacDive taxa2ec (grouped by bacdive_id)
bacdive_ec = bacdive_df[['bacdive_id','taxon_id','type_strain','ec']].copy()
bacdive_ec['taxon_id'] = bacdive_ec['taxon_id'].astype(str)
bacdive_ec['ec'] = bacdive_ec['ec'].str.replace("'", "")
bacdive_ec = bacdive_ec.rename(columns={'ec': 'ec_bacdive'})

# UniProtKB taxa2ec (grouped by species name)
uniprot_ec = uniprot_df.copy()
uniprot_ec['species'] = uniprot_ec['species'].replace(r'\+',' ', regex=True)
uniprot_ec['ec_uniprot'] = uniprot_ec['ec_uniprot'].str.replace(";", ",")
uniprot_ec = uniprot_ec.groupby("species", as_index=False)["ec_uniprot"].apply(lambda x: "[%s]" % ', '.join(x))

# NCBI taxa2ec (grouped by taxon_id)
ncbi_ec = ncbi_df.astype(str).copy()
ncbi_ec = ncbi_ec.rename(columns={'species': 'taxon_id', 'ec_uniprot': 'ec_ncbi'})
ncbi_ec = ncbi_ec.groupby("taxon_id", as_index=False)["ec_ncbi"].apply(lambda x: "[%s]" % ', '.join(x))

In [13]:
# Merge MediaDive dataframe with formatted outputs
media_df = pd.read_csv(os.path.join(DATA_DIR,"mediadive","mediadive-all.csv"), sep=";")

# Completing merge in multiple steps since we're merging on different columns
merged1 = pd.merge(left = media_df, right = uniprot_ec, on = 'species', how = 'left')
merged2 = pd.merge(left = merged1, right = bacdive_ec, on = 'bacdive_id', how = 'left')
merged3 = pd.merge(left = merged2, right = ncbi_ec, on = 'taxon_id', how = 'left')

merged3.to_csv(os.path.join(DATA_DIR, "taxa2ec-explode.csv"), index=False) #SAVE

In [14]:
# Melt ec columns and attribute ec source
final_df = merged3.melt(
    id_vars=["media_id", "species", "taxon_id"],
    value_vars=["ec_uniprot", "ec_bacdive", "ec_ncbi"],
    value_name="ec",
    var_name="source"
)

# Format source and ec columns
final_df["source"] = final_df["source"].str.replace("ec_", "")
final_df['ec'] = final_df['ec'].astype(str).copy()
final_df["ec"] = final_df["ec"].str.replace("[", "").str.replace("]", "")
final_df['ec'] = final_df['ec'].str.split(', ')
final_df = final_df.explode('ec')

# Remove rows with nan 'ec' values
final_df = final_df.copy()
substring = 'nan'
filter = final_df['ec'].str.contains(substring) # create filter
final_df = final_df[~filter]

final_df.to_csv(os.path.join(DATA_DIR, "taxa2ec-final.csv"), index=False) #SAVE
final_df

      media_id                 species   taxon_id   source          ec
1           1a  Comamonas testosteroni   216465.0  uniprot     2.6.1.1
1           1a  Comamonas testosteroni   216465.0  uniprot    4.1.1.12
1           1a  Comamonas testosteroni   216465.0  uniprot  1.13.11.74
1           1a  Comamonas testosteroni   216465.0  uniprot  1.13.11.76
1           1a  Comamonas testosteroni   216465.0  uniprot  1.14.13.23
...        ...                     ...        ...      ...         ...
60874    J1270  Neisseria meningitidis  1807135.0  bacdive     3.5.1.5
60874    J1270  Neisseria meningitidis  1807135.0  bacdive    3.2.1.23
60874    J1270  Neisseria meningitidis  1807135.0  bacdive    4.1.99.1
60874    J1270  Neisseria meningitidis  1807135.0  bacdive    4.1.1.17
60874    J1270  Neisseria meningitidis  1807135.0  bacdive     3.5.3.6

[1675019 rows x 5 columns]

### Some quick stats

Final media/taxa utilized in the 05-Model-Test.ipynb input and analyses

In [15]:
taxa = pd.read_csv(os.path.join(DATA_DIR, "taxa2ec-final.csv"), low_memory=False)
taxa = taxa.drop(["ec", "source"], axis=1).drop_duplicates()

filter1 = taxa.drop("species", axis=1).drop_duplicates()

media_list = filter1["media_id"].to_list()
media_set = set(media_list)

taxon_list = filter1["taxon_id"].to_list()
tax_set = set(taxon_list)

print(len(media_set), "media utilized in ml_input")
print(len(tax_set), "species utilized in ml_input")

648 media utilized in ml_input
6054 species utilized in ml_input

## Media to EC

3.1 KEGG (KEGG CPD) | Queries KEGG for ec numbers from an input of KEGG compounds (1.1)

3.2 UniProtKB (ChEBI) | Queries UniProtKB for ec numbers from an input of ChEBI IDs (1.1)

### [3.1] KEGG media2ec

In [16]:
import modules.kegg as kegg

# Retrieve 'component_ids' from the 'md_df' MediaDive dataframe
md_df = pd.read_csv(os.path.join(DATA_DIR,"mediadive","mediadive-all.csv"), sep = ';')

comps_df = md_df[['media_id','components','component_ids']].copy()
comps_df['media_id'] = comps_df['media_id'].drop_duplicates()
comps_df = comps_df.dropna()

# Extract the component_ids into a list
comps_df['component_ids'] = comps_df['component_ids'].astype(str)

def extract_ids(comps_df, component_ids):
    id_set = set()  # Use a set to avoid duplicate IDs
    for ids in comps_df['component_ids']:
        id_list = eval(ids)  # Convert the string representation of the list to an actual list
        id_set.update(id_list)
    return list(id_set)

# Extract IDs
id_list = extract_ids(comps_df, 'ids')

In [17]:
# Retrieve compound IDs from component IDs (MediaDive)
compound_df = md.get_compounds(id_list)

# Making 'cpd_list' using the KEGG compound IDs
cpd_df = compound_df['KEGG cpd'].dropna().copy()
cpd_list = cpd_df.to_list()

# Retrieve ECs from CPDs
cpd2ec_df = kegg.compound2ec(cpd_list) # HTTP errors = no ECs associated with this compound on KEGG

# Merge dataframes with component_id, compound, and ec information
cpd_merge = pd.merge(left=compound_df, right=cpd2ec_df, on="KEGG cpd", how="outer")
cpd_merge = cpd_merge.drop_duplicates()

cpd_merge.to_csv(os.path.join(DATA_DIR,"kegg","kegg-compound-ec.csv"), index=False) #SAVE

100%|██████████| 771/771 [10:29<00:00,  1.22it/s]

HTTP error occurred for C00293: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/compound:C00293
HTTP error occurred for C00382: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/compound:C00382

In [18]:
# Explode md_df on component_id
component_df = md_df.copy()
component_df['component_ids'] = md_df['component_ids'].str.strip('[]')
component_df['component_ids'] = component_df['component_ids'].str.split(', ').explode('component_ids')
component_df = component_df.rename(columns={'component_ids': 'component_id'})

# Merge md_df with media2ec (KEGG), remove NaN 'KEGG cpd' values
cpd_merge['component_id'] = cpd_merge['component_id'].astype(str)
comp_comp = pd.merge(left=component_df, right=cpd_merge, on='component_id', how='outer')
kegg2ec = comp_comp.loc[comp_comp['KEGG cpd'].notnull()].copy()
kegg2ec = kegg2ec.loc[kegg2ec['Enzyme'].notnull()]

#NOTE: not all 'component id's' have an associated 'KEGG compound', and not all 'KEGG compound's' have an associated 'Enzyme'...this means our final table has a loss of data from our original input
    #Can try to remedy the data loss by splitting complex media components into their simpler forms

# Load and format taxon_id's from bacdive dataframe
taxon_df = pd.read_csv(os.path.join(DATA_DIR,"bacdive","bacdive-all.csv"), low_memory=False)
taxon_df = taxon_df[['bacdive_id','taxon_id']]

# Merge taxon_id's to kegg2ec table
media_final = pd.merge(left=kegg2ec, right=taxon_df, on='bacdive_id', how='outer')
media_final = media_final[['media_id','taxon_id','component_id','KEGG cpd','Enzyme']].copy()
media_final = media_final.dropna(subset='Enzyme')

media_final.to_csv(os.path.join(DATA_DIR, "media2ec-final.csv"), index=False) #SAVE

In [19]:
media_final = pd.read_csv(os.path.join(DATA_DIR, "media2ec-final.csv"))

# Function to split the column by 6-9 spaces (variable delimitation...idk why)
def split_and_clean(value):
    # Split the string based on 6 to 9 spaces
    split_values = re.split(r'\s{6,9}', value)
    # Remove any remaining spaces from the split values
    split_values = [v.strip() for v in split_values]
    return split_values

# Split and Explode
media_final['split_column'] = media_final['Enzyme'].apply(split_and_clean).copy()
media_split = media_final.explode('split_column').reset_index(drop=True)
media_split = media_split.drop(columns=['Enzyme'])
media_split = media_split.rename(columns={'split_column': 'ec_KEGG'})
media_split['ec_KEGG'] = media_split['ec_KEGG'].dropna()

media_split.to_csv(os.path.join(DATA_DIR, "media2ec-explode.csv"), index=False) #SAVE
media_split.head()

  media_id  taxon_id  component_id KEGG cpd    ec_KEGG
0     J598     435.0             4   C00001    1.1.1.1
1     J598     435.0             4   C00001   1.1.1.22
2     J598     435.0             4   C00001   1.1.1.23
3     J598     435.0             4   C00001  1.1.1.115
4      J25  169875.0             4   C00001    1.1.1.1

### [3.2] ChEBI media2ec

In [20]:
#TODO: add viable ChEBI compound media2ec (previously too memory-intensive, too many hits from UniProtKB)

## EC to Cofactors

In [ ]:
import modules.cofactors as cofactors

df = pd.read_csv(os.path.join(DATA_DIR, 'taxa2ec-final.csv'), low_memory=False)

taxa_ec_list = df['ec'].to_list() 
taxa_ecs = set(taxa_ec_list) # create a set of unique ECs, (also .isunique()), but remerge on taxa2ec for counts
taxa_ec_list = list(taxa_ecs)

print(len(taxa_ec_list), "EC numbers")

# Retrieve cofactors
taxa_cofactors = cofactors.ec2metals(taxa_ec_list) # takes ~2.5-3 hours for ~4000 ec numbers
taxa_cofactors.head()

3954 EC numbers

100%|██████████| 3954/3954 [1:11:48<00:00,  1.09s/it]

,Query EC,Entry,Entry Name,Gene Names,Organism,Organism (ID),Taxonomic lineage,Taxonomic lineage (Ids),Protein names,Binding site,...,BioCyc,BRENDA,PathwayCommons,Reactome,InterPro,Pfam,CofactorExtracted,CofactorNormalized,Fe-S cluster,CofactorFinal
0,3.1.3.18,P32662,GPH_ECOLI,gph yhfE b3385 JW3348,Escherichia coli (strain K12),83333,"cellular organisms (no rank), Bacteria (domain...","131567 (no rank), 2 (domain), 3379134 (kingdom...",Phosphoglycolate phosphatase (PGP) (PGPase) (E...,"BINDING 13..15; /ligand=""substrate""; /evidence...",...,EcoCyc:GPH-MONOMER;MetaCyc:GPH-MONOMER;,NaN,NaN,NaN,IPR050155;IPR036412;IPR006439;IPR023214;IPR023...,PF00702;,chloride,Cl,False,Cl
1,3.1.3.18,P32662,GPH_ECOLI,gph yhfE b3385 JW3348,Escherichia coli (strain K12),83333,"cellular organisms (no rank), Bacteria (domain...","131567 (no rank), 2 (domain), 3379134 (kingdom...",Phosphoglycolate phosphatase (PGP) (PGPase) (E...,"BINDING 13..15; /ligand=""substrate""; /evidence...",...,EcoCyc:GPH-MONOMER;MetaCyc:GPH-MONOMER;,NaN,NaN,NaN,IPR050155;IPR036412;IPR006439;IPR023214;IPR023...,PF00702;,Mg(2+),Mg,False,Mg
2,3.1.3.18,O67359,GPH_AQUAE,gph aq_1342,Aquifex aeolicus (strain VF5),224324,"cellular organisms (no rank), Bacteria (domain...","131567 (no rank), 2 (domain), 3379134 (kingdom...",Phosphoglycolate phosphatase (PGP) (PGPase) (E...,"BINDING 7; /ligand=""Mg(2+)""; /ligand_id=""ChEBI...",...,NaN,3.1.3.18;,NaN,NaN,IPR050155;IPR036412;IPR006439;IPR041492;IPR023...,PF13419;,Mg(2+),Mg,False,Mg
3,3.1.3.18,Q9HLQ2,PGP_THEAC,Ta0175,Thermoplasma acidophilum (strain ATCC 25905 / ...,273075,"cellular organisms (no rank), Archaea (domain)...","131567 (no rank), 2157 (domain), 3366610 (king...",Phosphoglycolate phosphatase (PGP) (PGPase) (E...,"BINDING 8; /ligand=""Mg(2+)""; /ligand_id=""ChEBI...",...,NaN,3.1.3.18;,NaN,NaN,IPR036412;IPR023214;IPR006382;,PF08282;,Mg(2+),Mg,False,Mg
4,3.1.3.18,A3PNX3,GPH_CERS1,cbbZ Rsph17029_2937,Cereibacter sphaeroides (strain ATCC 17029 / A...,349101,"cellular organisms (no rank), Bacteria (domain...","131567 (no rank), 2 (domain), 3379134 (kingdom...",Phosphoglycolate phosphatase (PGP) (PGPase) (E...,"BINDING 7; /ligand=""Mg(2+)""; /ligand_id=""ChEBI...",...,NaN,NaN,NaN,NaN,IPR050155;IPR036412;IPR006439;IPR023214;IPR023...,PF00702;,Mg(2+),Mg,False,Mg

In [23]:
# Format ec2metals output
#cofactors = cofactor_df.drop_duplicates().copy()
cofactors = taxa_cofactors.drop_duplicates().copy()
cofactors = cofactors.dropna(subset=['CofactorExtracted']).copy()

# List out all cofactors
CofactorFinal = cofactors.drop_duplicates(subset=['Query EC','CofactorFinal']).copy()
CofactorFinal.to_csv(os.path.join(DATA_DIR, "cofactors", "cofactors-taxa.csv"), index=False) #SAVE

# Group cofactors by EC
grouped_cofactors = CofactorFinal.groupby("Query EC", as_index=False)["CofactorFinal"].apply(lambda x: "[%s]" % ', '.join(x))
grouped_cofactors.to_csv(os.path.join(DATA_DIR, "cofactors", "cofactors-taxa-grouped.csv"), index=False) #SAVE

grouped_cofactors.head()

    Query EC                                      CofactorFinal
0    1.-.-.-  [Fe, Zn, S, Mg, Ca, pyrroloquinoline quinone, ...
1    1.1.-.-  [Zn, Mg, Ca, pyrroloquinoline quinone, Fe, S, ...
2    1.1.1.-  [Zn, Mg, metal, K, FAD, Fe, S, Mn, Ni, FMN, Cu...
3    1.1.1.1                                           [Zn, Fe]
4  1.1.1.103                                               [Zn]

## EC to KO

In [24]:
taxa_ec = pd.read_csv(os.path.join(DATA_DIR, "taxa2ec-final.csv"), low_memory=False)

# Filter non-sepcific EC numbers (e.g., 1.1.1.-)
filter = taxa_ec["ec"].str.contains("-")
taxa_ec = taxa_ec[~filter]

# Make into a list of unique ECs
ec_list = taxa_ec["ec"].to_list()
ec_list = set(ec_list)
ec_list = list(ec_list)

# Retrieve KOs from KEGG
ec2ko_df = kegg.ec2ko(ec_list)

# Merge on original dataframe
ko_df = pd.merge(left=taxa_ec, right=ec2ko_df, on="ec", how="left")

ko_df.to_csv(os.path.join(DATA_DIR, 'kegg', 'ec2ko-taxa.csv'), index=False) #SAVE
ko_df.head()

# TODO: use the taxa2ec and media2ec lists as inputs, then use KEGG decoder

HTTP error occurred for 2.3.1.n4: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:2.3.1.n4
HTTP error occurred for 2.7.7.n6: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:2.7.7.n6
HTTP error occurred for 3.2.1.n2: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:3.2.1.n2
HTTP error occurred for 1.1.1.n12: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.1.1.n12
HTTP error occurred for 3.2.1.n1: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:3.2.1.n1
HTTP error occurred for 4.2.2.n2: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:4.2.2.n2
HTTP error occurred for 6.2.1.n2: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:6.2.1.n2
HTTP error occurred for 4.2.2.n1: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:4.2.2.n1
HTTP error occurred for 3.2.2.n1: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:3.2.2.n1
HTTP error occurred for 1.1.1.n4: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.1.1.n4
HTTP error occurred for 3.6.5.n1: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:3.6.5.n1
HTTP error occurred for 1.14.19.n5: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.14.19.n5
HTTP error occurred for 2.3.1.n7: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:2.3.1.n7
HTTP error occurred for 2.5.1.n9: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:2.5.1.n9
HTTP error occurred for 1.3.99.n1: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.3.99.n1
HTTP error occurred for 3.5.1.n3: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:3.5.1.n3
HTTP error occurred for 1.14.19.n4: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.14.19.n4
HTTP error occurred for 1.3.1.n3: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.3.1.n3
HTTP error occurred for 1.2.1.n2: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.2.1.n2
HTTP error occurred for 1.1.1.n5: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:1.1.1.n5
HTTP error occurred for 2.3.1.n5: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:2.3.1.n5
HTTP error occurred for 3.5.1.B15: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:3.5.1.B15
HTTP error occurred for 2.1.1.n11: 404 Client Error: Not Found for url: https://rest.kegg.jp/get/ec:2.1.1.n11

,media_id,species,taxon_id,source,ec,KO
0,1a,Comamonas testosteroni,216465.0,uniprot,2.6.1.1,"K00811 aspartate aminotransferase, chloroplas..."
1,1a,Comamonas testosteroni,216465.0,uniprot,4.1.1.12,K09758 aspartate 4-decarboxylase
2,1a,Comamonas testosteroni,216465.0,uniprot,1.13.11.74,K15059 2-aminophenol/2-amino-5-chlorophenol 1...
3,1a,Comamonas testosteroni,216465.0,uniprot,1.13.11.76,K15059 2-aminophenol/2-amino-5-chlorophenol 1...
4,1a,Comamonas testosteroni,216465.0,uniprot,1.14.13.23,K19065 3-hydroxybenzoate 4-monooxygenase

## Metabolites

In [25]:
# Format BacDive metabolite information
bacdive_df = pd.read_csv(os.path.join(DATA_DIR, 'bacdive', 'bacdive-all.csv'), low_memory=False) #Additonal references and other info also available

mtblt = bacdive_df[[
    "bacdive_id",
     "taxon_id",
     "compound_production_compound",
     "metabol_uti",
     "chebi_id",
     "metabol_name",
     "metabol_production", 
     "isolation,_sampling_and_environmental_information_isolation"
]].copy()

mtblt.to_csv(os.path.join(DATA_DIR, "bacdive", "metabolites.csv"), index=False) #SAVE

In [26]:
mtblt["metabol_uti"] = mtblt["metabol_uti"].astype(str)
mtblt["metabol_uti"] = mtblt["metabol_uti"].dropna()
filter = mtblt["metabol_uti"].str.contains("nan")
mtblt = mtblt[~filter]

# Apply function
expanded_df = utils.expand_dict_list(mtblt, 'metabol_uti')

# Reapply nan filter for the newly expanded data
expanded_df = expanded_df.copy()
expanded_df["utilization activity"] = expanded_df["utilization activity"].astype(str)
expanded_df["utilization activity"] = expanded_df["utilization activity"].dropna()
filter2 = expanded_df["utilization activity"].str.contains("nan")
expanded_df = expanded_df[~filter2]

# Subset and save metabolite utilization information
metabol_uti = expanded_df[[
    "bacdive_id",
    "taxon_id",
    "Chebi-ID",
    "metabolite",
    "utilization activity",
    "kind of utilization tested",
    "isolation,_sampling_and_environmental_information_isolation"
    ]]
metabol_uti = metabol_uti.rename(columns={
    "Chebi-ID": "chebi_id",
    "isolation,_sampling_and_environmental_information_isolation": "isolation_info"
    })

metabol_uti.to_csv(os.path.join(DATA_DIR, "bacdive", "metabol_uti.csv"), index=False) #SAVE
metabol_uti.head()

,bacdive_id,taxon_id,chebi_id,metabolite,utilization activity,kind of utilization tested,isolation_info
0,24370,294.0,17306.0,maltose,-,assimilation,NaN
1,24370,294.0,25115.0,malate,+,assimilation,NaN
2,24370,294.0,17128.0,adipate,-,assimilation,NaN
3,24370,294.0,27689.0,decanoate,+,assimilation,NaN
4,24370,294.0,24265.0,gluconate,+,assimilation,NaN

In [27]:
mtblt["metabol_production"] = mtblt["metabol_production"].astype(str).copy()

# Subset rows with confirmed metabolite production
substring = 'yes'
filter = mtblt["metabol_production"].str.contains(substring)
metabol_pro = mtblt[filter]

# Subset and save metabolite production information
metabol_pro = metabol_pro[[
    "bacdive_id",
    "taxon_id",
    "chebi_id",
    "metabol_name",
    "metabol_production",
    "isolation,_sampling_and_environmental_information_isolation"
    ]]
metabol_pro = metabol_pro.rename(columns={
    "metabol_name": "metabolite",
    "isolation,_sampling_and_environmental_information_isolation": "isolation_info"
    })

metabol_pro.to_csv(os.path.join(DATA_DIR, "bacdive", "metabol_pro.csv"), index=False) #SAVE
metabol_pro.head()

,bacdive_id,taxon_id,chebi_id,metabolite,metabol_production,isolation_info
63,5030,53336.0,35581.0,indole,yes,NaN
95,347,221992.0,35581.0,indole,yes,"[{'@ref': 4618, 'sample type': 'ditch in a for..."
96,346,106590.0,35581.0,indole,yes,"[{'@ref': 4617, 'sample type': 'activated slud..."
180,5050,553088.0,35581.0,indole,yes,"[{'@ref': 16317, 'sample type': '<i>Heterorhab..."
181,5036,396808.0,35581.0,indole,yes,"[{'@ref': 5632, 'sample type': 'nematode <I>He..."

## Environmental Parameters

In [28]:
# Subsetting MediaDive dataframe
md_df = pd.read_csv(os.path.join(DATA_DIR,"taxa2ec-explode.csv"), low_memory=False)

# Format pH data as a range
def create_range(row):
    if row['min_pH'] == row['max_pH']:
        return f"{row['min_pH']}"
    else:
        return f"{row['min_pH']}-{row['max_pH']}"
md_df['pH'] = md_df.apply(create_range, axis=1)
md_df = md_df[["media_id", "name", "pH","components", "component_ids", "species", "ccno", "bacdive_id", "ec_bacdive","ec_uniprot","ec_ncbi"]]

# BacDive dataframe
bd_df = pd.read_csv(os.path.join(DATA_DIR, "bacdive", "bacdive-all.csv"), low_memory=False)
bd_df = bd_df[[
    "bacdive_id",
    "taxon_id",
    "culture_and_growth_conditions_culture_medium",
    "culture_temp_@ref",
    "culture_temp_growth",
    "culture_temp_type",
    "culture_temp_temperature",
    "isolation_sample_type",
    "isolation,_sampling_and_environmental_information_isolation",
    "oxygen_tolerance_oxygen_tolerance",
    "physiology_and_metabolism_halophily",
    "antibiotic_resistance_metabolite",
    "antibiotic_resistance_is_antibiotic",
    "antibiotic_resistance_is_sensitive",
    "antibiotic_resistance_is_resistant"
]]

# Merge dataframes
dive = pd.merge(left=md_df, right=bd_df, on="bacdive_id", how="left")
dive.head()

,media_id,name,pH,components,component_ids,species,ccno,bacdive_id,ec_bacdive,ec_uniprot,...,culture_temp_type,culture_temp_temperature,isolation_sample_type,"isolation,_sampling_and_environmental_information_isolation",oxygen_tolerance_oxygen_tolerance,physiology_and_metabolism_halophily,antibiotic_resistance_metabolite,antibiotic_resistance_is_antibiotic,antibiotic_resistance_is_sensitive,antibiotic_resistance_is_resistant
0,1,NUTRIENT AGAR,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1a,REACTIVATION WITH LIQUID MEDIUM 1,7.0,"['Peptone', 'Meat extract', 'Agar', 'Distilled...","[1, 2, 3, 4]",Comamonas testosteroni,DSM 38,2912.0,"[1.9.3.1, 3.2.1.21, 3.5.1.5, 3.5.3.6]","[2.6.1.1, 4.1.1.12, 1.13.11.74, 1.13.11.76, 1....",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1a,REACTIVATION WITH LIQUID MEDIUM 1,7.0,"['Peptone', 'Meat extract', 'Agar', 'Distilled...","[1, 2, 3, 4]",Delftia acidovorans,DSM 39,2941.0,"[3.5.1.5, 1.9.3.1, 3.2.1.21, 3.5.3.6]","[1.14.11.43, 1.14.11.44, 3.1.1.75, 6.3.4.2, 2....",...,NaN,NaN,NaN,"[{'@ref': 2038, 'sample type': 'soil enriched ...",NaN,NaN,NaN,NaN,NaN,NaN
3,1a,REACTIVATION WITH LIQUID MEDIUM 1,7.0,"['Peptone', 'Meat extract', 'Agar', 'Distilled...","[1, 2, 3, 4]",Acidovorax delafieldii,DSM 64,2885.0,"[3.2.1.51, 3.2.1.24, 3.2.1.52, 3.2.1.21, 3.2.1...",[1.1.1.37],...,NaN,NaN,NaN,"[{'@ref': 2047, 'sample type': 'soil, enrichme...",obligate aerobe,"[{'@ref': 118877, 'salt': 'NaCl', 'growth': 'p...","0129 (2,4-Diamino-6,7-di-iso-propylpteridine p...",yes,no,yes
4,1a,REACTIVATION WITH LIQUID MEDIUM 1,7.0,"['Peptone', 'Meat extract', 'Agar', 'Distilled...","[1, 2, 3, 4]",Pseudomonas putida,DSM 84,12895.0,"[3.5.1.5, 3.2.1.21, 3.5.3.6]","[5.1.1.10, 5.3.3.1, 1.18.1.3, 1.2.98.1, 1.18.1...",...,growth,26,sewage,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# MAG Processing:

Note: EC-annotated MAG parsing is for DRAM outputs, may need to change based on file format. KO-annotated MAGs are for those with a list of KO numbers which need no further formatting. DRAM also outputs KO numbers, so this can be updated if needed to pull those as well.

## For parsing EC-annotated .gff's:

In [ ]:
#TODO: make this section more generalized, or even into its own notebook? 
# Can also make a script where you pass a .gff file it automatically formats it for the input.

In [30]:
import modules.utils as utils

directory = os.path.join(DATA_DIR, "MAGs", "FENIX21", "DRAM", "all") #can also separate sediments / fluids
bins = utils.process_directory(directory) # Parse .gff files for ec numbers

bins.to_csv(os.path.join(DATA_DIR, 'MAGs', 'FENIX21', 'FENIX21-all.csv'), index=False)

test_ecs = bins.copy()
filter = test_ecs["ec"].str.contains("N/A")
test_ecs = test_ecs[~filter]

print(len(test_ecs), "annotations")
test_ecs.head()

Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaBA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaCF_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaCG_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaFE_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaGA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaLS_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaML_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaPI_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaPI_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaSI_1_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaSN_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaSP_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.001.fastaVR_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaBA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaCF_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaCG_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaGA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaGA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaLS_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaLS_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaPI_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaPI_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaSI_1_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaSI_1_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaSI_2_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.002.fastaSP_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaCF_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaCG_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaCG_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaFE_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaGA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaLS_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaPI_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaPI_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaSI_1_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaSI_2_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaSP_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaSP_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.003.fastaVR_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaBA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaCF_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaCG_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaCG_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaLS_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaLS_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaPI_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaPI_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaSI_1_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaSN_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaSP_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.004.fastaSP_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaBA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaCA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaCF_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaCG_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaGA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaLS_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaLS_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaML_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaPI_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaSI_1_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaSI_1_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.005.fastaSN_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaBA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaCA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaCF_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaCG_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaLS_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaLS_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaPI_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaPI_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaSI_1_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaSN_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaSP_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaSP_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.006.fastaVR_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaCF_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaCG_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaLS_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaLS_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaPI_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaSI_1_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaSN_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaSP_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaSP_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.007.fastaVR_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaBA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaBA_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaCA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaCG_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaGA_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaLS_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaPI_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaSI_1_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaSI_2_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaSP_F_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.008.fastaSP_S_extracted_bins.AssemblySet_DRAM.gff
Processing file: C:/Users/jakel/Desktop/Projects/Media_Prediction/media_prediction/data\MAGs\FENIX21\DRAM\all\KBase_derived_Bin.009.fastaBA_F_extracted_bins.AssemblySet_DRAM.gff

,filename,seqname,source,feature,ID,product,ec,ko
3,KBase_derived_Bin.001.fastaBA_F_extracted_bins...,NODE_1052_length_11999_cov_4.021266,KBase,gene,NODE_1052_length_11999_cov_4.021266_4,release factor glutamine methyltransferase %5B...,2.1.1.297,KO:K02493
5,KBase_derived_Bin.001.fastaBA_F_extracted_bins...,NODE_1052_length_11999_cov_4.021266,KBase,gene,NODE_1052_length_11999_cov_4.021266_6,histidyl-tRNA synthetase %5BEC:6.1.1.21%5D,6.1.1.21,KO:K01892
13,KBase_derived_Bin.001.fastaBA_F_extracted_bins...,NODE_1109_length_11407_cov_3.999383,KBase,gene,NODE_1109_length_11407_cov_3.999383_3,type III pantothenate kinase %5BEC:2.7.1.33%5D,2.7.1.33,KO:K03525
29,KBase_derived_Bin.001.fastaBA_F_extracted_bins...,NODE_1114_length_11353_cov_4.046645,KBase,gene,NODE_1114_length_11353_cov_4.046645_8,tRNA-uridine 2-sulfurtransferase %5BEC:2.8.1.1...,2.8.1.13,KO:K00566
36,KBase_derived_Bin.001.fastaBA_F_extracted_bins...,NODE_1141_length_11155_cov_4.291892,KBase,gene,NODE_1141_length_11155_cov_4.291892_2,branched-chain amino acid aminotransferase %5B...,2.6.1.42,KO:K00826

In [ ]:
#TODO: update this so it doesn't include FENIX / etc. -- just formats dataframes for the ml_input used by 02 and 03 .ipynb's

In [31]:
# Load dataframes
train = pd.read_csv(os.path.join(DATA_DIR, "taxa2ec-final.csv"), low_memory=False)
test = pd.read_csv(os.path.join(DATA_DIR, 'MAGs', 'FENIX21', 'FENIX21-all.csv'), low_memory=False)

# Weird na values, just make some filters
test["ec"] = test["ec"].astype(str).dropna()
NaN = test["ec"].str.contains("NaN")
nan = test["ec"].str.contains("nan")
test = test[~NaN & ~nan]

# Start formatting to merge with taxa2ec-final
test["media_id"] = "unknown"
test["species"] = "unknown" ### can update with taxonomy predictions from the KBase workspace
test = test.rename(columns={"filename": "taxon_id", "ID": "node"})

# Subset and Concat
test = test[["media_id","species","taxon_id", "source", "ec"]]
frames = train, test
ml_input = pd.concat(frames)

#ml_input.to_csv(os.path.join(DATA_DIR, "model", "ml_input.csv"), index=False)
ml_input

,media_id,species,taxon_id,source,ec
0,1a,Comamonas testosteroni,216465.0,uniprot,2.6.1.1
1,1a,Comamonas testosteroni,216465.0,uniprot,4.1.1.12
2,1a,Comamonas testosteroni,216465.0,uniprot,1.13.11.74
3,1a,Comamonas testosteroni,216465.0,uniprot,1.13.11.76
4,1a,Comamonas testosteroni,216465.0,uniprot,1.14.13.23
...,...,...,...,...,...
590610,unknown,unknown,KBase_derived_Bin.039.fastaLS_S_extracted_bins...,KBase,2.7.1.107
590612,unknown,unknown,KBase_derived_Bin.039.fastaLS_S_extracted_bins...,KBase,1.7.2.5
590618,unknown,unknown,KBase_derived_Bin.039.fastaLS_S_extracted_bins...,KBase,3.2.1.81
590619,unknown,unknown,KBase_derived_Bin.039.fastaLS_S_extracted_bins...,KBase,3.1.21.7
590623,unknown,unknown,KBase_derived_Bin.039.fastaLS_S_extracted_bins...,KBase,3.5.4.33

## For KO-annotated MAGs:

In [ ]:
#TODO: generalize and script this as well:

In [32]:
# # Load ko-annotated MAG (LCHF)
# mag = pd.read_csv(os.path.join(DATA_DIR, "Thermodesulfo_MAG.csv"))
# mag = mag.dropna()
# ko_list = mag["KO"].to_list()

# def fetch_and_extract_ec_numbers(ko):
#     url = f'https://rest.kegg.jp/get/ko:{ko}'
#     response = requests.get(url)
    
#     if response.status_code == 200:
#         data = response.text
#         ec_numbers = re.findall(r'\b\d+\.\d+\.\d+\.\d+\b', data)
#         return ec_numbers
#     else:
#         print(f"Failed to retrieve data for KO: {ko}")
#         return []

# all_ec_numbers = {}
# for ko in ko_list:
#     ec_numbers = fetch_and_extract_ec_numbers(ko)
#     all_ec_numbers[ko] = ec_numbers

# data_for_df = []
# for ko, ec_numbers in all_ec_numbers.items():
#     for ec in ec_numbers:
#         data_for_df.append({'KO': ko, 'EC Number': ec})
# df = pd.DataFrame(data_for_df)

# cp = df.copy()
# x = "LC_bin_0"
# y = "unknown"
# z = "Thermodesulfovibrionales"
# s = "MAG"
# cp[["taxon_id","media_id", "species", "source"]] = x, y, z, s
# cp = cp.rename(columns={"EC Number":"ec"})

# cp.to_csv(os.path.join(DATA_DIR, "MAGs", "test.csv"))


# # Merge our results
# taxa = pd.read_csv(os.path.join(DATA_DIR, "taxa2ec-final.csv"), low_memory=False)
# cp = pd.read_csv(os.path.join(DATA_DIR, "MAGs", "test.csv"))
# test = cp[["media_id", "species", "taxon_id", "source", "ec"]]
# data = [test, taxa]
# model = pd.concat(data)

# #model.to_csv(os.path.join(DATA_DIR, "test_model.csv"), index=False)
# model.head()